### ISSUE TITLE
how can I know it works or not?

### ISSUE THREAD

**Issue by hdjeong80** [duraki/SketchCrapp#10]
I saw this message, [+] SketchCrapp process completed. Sketch.app has been patched :)

but how can I know it really works or not?

Is it the only way to wait for 30 days to expire?

**Comment by elijahtsai** [comment]
Hi @hdjeong80, Yes, currently the only way to verify is waiting trial to expire. But if patch process result successfully, then there has very high chances it’s really success. If you still get the register license window pop up after trial over please let us know.

**Comment by duraki** [comment]
The best way is to compare hashes between cracked/patched binary, and one prior to cracking/running the script. Not an issue per se and not related to SketchCrapp. Closing.
