### ISSUE TITLE
binaryerr›› should detect if Version is not supported

### ISSUE THREAD

**Issue by duraki** [duraki/SketchCrapp#17]
Due to #15 and #16, we need to add support for `binaryerr` to check supported hashes via binary Mach-O, and report the end-user that the version is not yet supported.

ie. If hash is not in the list, nor does match supported version, it's probably:
* an unsupported version 
* a broken binary 

```
+ Issue details ‹s:sketchcrapp›
+ Application Path  : /Users/xxxx/Downloads/Sketch.app
+ Application Binary: /Users/xxxx/Downloads/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : ‹nil›
+ Binary SHA1       : bc22987f7b3a7580aba1ac260c59d66d0a3622e7
+ Error             : binaryerr›› [version not supported]
+                     supported versions are [v1, ..., v(n)]
+===================================================================
```

We can further read `*.plist` under app directory to detect which version did user try to patch. This way we can diff between a broken binary or given version. For example, if `plist` version is supported (ie. v61.1), it's a broken binary; if `plist` version is not yet supported, it needs a SketchCrapp update and obviously some more reverse-engineering.

> [version v(n) is not yet supported]

@elijahtsai wdyt?

**Comment by elijahtsai** [comment]
This is totally what I think!!!😂

**Comment by duraki** [comment]
That was fast :) Nice work @elijahtsai! 🚀

**Comment by elijahtsai** [comment]
Haha! closed 3 issue a day, never tried
