### ISSUE TITLE
Move from ZSH to Bash

### ISSUE THREAD

**Issue by duraki** [duraki/SketchCrapp#2]
We need to move from `zsh` to `bash` as it's the default shell on most MacOS (comes preinstalled). `Zsh` may give headache to those who don't have it installed.

https://github.com/duraki/SketchCrapp/blob/988493432a8580fa715be664edda740789427398/sketchcrapp.sh#L1

We may need to refactor the code for declarative syntax (offsets), this now throws:

```
sketchcrapp.sh: 88: declare: not found
: not found.sh: 89: value_param_672+=
: not found.sh: 90: value_param_672+=
: not found.sh: 91: value_param_672+=
: not found.sh: 92: value_param_672+=
```

WDYT @elijahtsai

**Comment by elijahtsai** [comment]
I changed the shebang from zsh to bash. but my macOS version is 10.15. so still need to check if it really supports lower versions.
