### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sameerthapaevontech** [duraki/SketchCrapp#22]
**Describe the issue [required]**
This is not working

**macOS version [required]**
macOS Mojave 10.14.6

**Sketch version [required]**
68.1

**Terminal error message [required]**
+===================================================================
+ Issue details ‹s:sketchcrapp›
+ Application Path  : /Applications/Sketch.app
+ Application Binary: /Applications/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : 68.1
+ Correct hash      : bc22987f7b3a7580aba1ac260c59d66d0a3622e7
+ Binary SHA1       : f397bde66f21734afaf018000eb592fa86672171
+ Error             : Can’t look up version from hash.
+===================================================================

**Additional context [optional]**

**Screenshots [optional]**

**Comment by elijahtsai** [comment]
Hi, @sameerthapaevontech It seems like your application bundle has got modify before, please download the package again from the official website, unzip it and patch again. try not to open the application before the patch process complete.

**Comment by elijahtsai** [comment]
Script had updated! Remember to download the latest script before you try again.😄

**Comment by duraki** [comment]
Lets say it works for now. I will close it to keep the clutter away.

**Comment by llure** [comment]
Hi!
I'm in Big Sur.
I found this:

  #openssl pkcs12 -export -legacy -out pkcs.p12 -in crt.pem -inkey pk.pem \
  openssl pkcs12 -export -out pkcs.p12 -in crt.pem -inkey pk.pem \
  -name "sketchcrapp" -nodes -passout pass:1234

**Comment by duraki** [comment]
> Hi!
> I'm in Big Sur.
> I found this:
> 
>   #openssl pkcs12 -export -legacy -out pkcs.p12 -in crt.pem -inkey pk.pem \
>   openssl pkcs12 -export -out pkcs.p12 -in crt.pem -inkey pk.pem \
>   -name "sketchcrapp" -nodes -passout pass:1234

It's normal. It's a self-signed certificate that is used to bypass the cert pinning mechanism. Read the blogpost in the README file.

**Comment by llure** [comment]
Hey!

Thank you!

I mean I solved my issue removing "-legacy". 

Just that,

thank you again

**Comment by duraki** [comment]
@llure: Sorry, figured out you were curious about why is that cert. in your Keychain. My bad, was out of the loop with this issue.

Btw. thanks for sharing hint on `-legacy` flag. We can deffo implement this to master branch to base-of "Big Sur vs [Others]" versioning and difference in OS expected flags.

**Comment by llure** [comment]
> [@llure](https://github.com/llure): Sorry, figured out you were curious about why is that cert. in your Keychain. My bad, was out of the loop with this issue.
> 
> Btw. thanks for sharing hint on `-legacy` flag. We can deffo implement this to master branch to base-of "Big Sur vs [Others]" versioning and difference in OS expected flags.

Thank you again!

you know more than me! :)

my openssl version is LibreSSL 2.8.3 , I dunno if this may help!

:)
