### ISSUE TITLE
Cracked but still showing (Register Now) on the top right corner

### ISSUE THREAD

**Issue by mianaliasjad** [duraki/SketchCrapp#25]
**Describe the issue [required]**
I have cracked the sketch with all the steps mentioned in the read-me. But when I open sketch it still showing 5 days left Register Now in the top right corner.

**macOS version [required]**
What is the macOS version?
macOS Catalina 10.15.6

**Sketch version [required]**
What is the Sketch version you want to patch?
68.2

**Terminal error message [required]**
No error in the terminal
`[+] Cleaning up certificate file(s)
[+] Cleaned
[+] SketchCrapp process completed. Sketch.app has been patched :)
[+] -- Notice: 
[+] If a dialogue shows up with message: “Sketch 3.app” can’t be opened
[+] please right-click the application and select open, or go to Settings -› Security
[+] and allow opening Sketch.app application.`

**Comment by elijahtsai** [comment]
Hi, @mianaliasjad The days left you saw is not related to patch process, the only thing you need to notice is that does it pop up any licence window at the application startup if not it’s good👍🏻

**Comment by duraki** [comment]
See #11 & #8

Closing.
