### ISSUE TITLE
[New version request] Sketch 69.1

### ISSUE THREAD

**Issue by p-nicolaou** [duraki/SketchCrapp#30]
**Sketch version [required]**
What is the Sketch version you want to patch?
Ex: 69.1

**Additional context [optional]**
According to Sketch, 69.1 resolves some crashes occurring while running on macOS Big Sur
https://www.sketch.com/updates/#version-69.1

**Comment by duraki** [comment]
Hopefully soon. Both @elijahtsai and me are a bit busy these days so don't expect it anytime soon.

**Comment by p-nicolaou** [comment]
SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[ERR] Version 69.1 is not supported, please carefully review README file again.
[INFO] Copy the details below and open a new issue on GitHub repository: https://github.com/duraki/SketchCrapp
+===================================================================
+ Issue details ‹s:sketchcrapp›
+ Application Path  : /Applications/Sketch.app
+ Application Binary: /Applications/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : 69.1
+ Binary SHA1       : 4ce06aa34c40040244c60608a02c152186f23c32
+ Error             : Version 69.1 is not supported.
+===================================================================

**Comment by elijahtsai** [comment]
@p-nicolaou Have you redownload our script yet?

**Comment by p-nicolaou** [comment]
Hi @elijahtsai. Thank you for your quick response. Manually replacing the content of my local `sketchcrapp.sh` with the latest, fixes the problem.
