### ISSUE TITLE
[Old version request] Version 58

### ISSUE THREAD

**Issue by RetributionAngel** [duraki/SketchCrapp#31]
_**Describe the request [required]**_
I currently have **58**, and I cannot update it since I am on a virtual machine without metal support. When I tried to install your patch, I got an error message saying it does not support my version.

_**Sketch version [required]**_
**58**

_**Additional context [optional]**_
I’m on a virtual machine, and **58** is as far as I can go without metal support.

**Comment by elijahtsai** [comment]
Hi, @RetributionAngel First thanks for trying out our project, but I and @duraki currently are a bit busy, we will try to look at the project to support 58 as soon as possible. 
**P.S. We do not guarantee any version can be supported before we release the script that can actually be supported.**

**Comment by elijahtsai** [comment]
@RetributionAngel We had found the solution, you can wait for our next release at any time.
