### ISSUE TITLE
Describe the magic function

### ISSUE THREAD

**Issue by duraki** [duraki/SketchCrapp#32]
I just used `-m` on a fresh MacOS install and it works flawlessly. We need to describe this magic function in the README.

**Comment by elijahtsai** [comment]
I know right!! 👍🏻
The function check everything before doing anything, I code it as close as possible to be fail-safe.

**Comment by duraki** [comment]
I presume it downloads the latest working version by SketchCrapp, right? This will come in handy soon =)

**Comment by elijahtsai** [comment]
Yeah ~ I hardcode the latest support version’s url  😂 First reason is make sure script will work , second reason is I’m too lazy to read the version list xml file just to get the url 😂😂😂

**Comment by duraki** [comment]
Appreciate this one too! 🥇
