### ISSUE TITLE
[New version request] Sketch 69.2

### ISSUE THREAD

**Issue by ESOlv** [duraki/SketchCrapp#35]
**Sketch version [required]**
What is the Sketch version you want support for?
69.2

**Additional context [optional]**
Sketch 69.2 not supported yet, on Mac OS Catalina 10.15.7

**Issue details **
[ERR] Version 69.2 is not supported, please carefully review README file again.
[INFO] Copy the details below and open a new issue on GitHub repository: https://github.com/duraki/SketchCrapp
+===================================================================
+ Issue details ‹s:sketchcrapp›
+ Application Path  : /Applications/Sketch.app
+ Application Binary: /Applications/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : 69.2
+ Binary SHA1       : a7ba7ddf8e15e1e03ae88c00ab5070dabecc06b2
+ Error             : Version 69.2 is not supported.
+===================================================================

**Comment by elijahtsai** [comment]
@ESOlv Script was updated!!! 🎊🎊🎊 Remember, make sure you redownload our script from the repository before you try to patch again.
