### ISSUE TITLE
Error on running the command

### ISSUE THREAD

**Issue by kirancornelio** [duraki/SketchCrapp#39]
**Describe the issue [required]**
A clear and concise description of what the issue is.
When I run the command on the system for the last step, get the below error.

SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... Error
[ERR] Can't find Sketch with that signature. Hash is invalid.
[INFO] Carefully review README file again
[INFO] If you still have problem copy the details below and open a new issue
[INFO] on GitHub repository: https://github.com/duraki/SketchCrapp
+===================================================================
+ Application Path  : /Applications/Sketch.app
+ Application Binary: /Applications/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : 69
+ Correct hash      : 2d4027890e2b72175c4a562f59c5d1adb2655b8c
+ Binary SHA1       : 85bc07b0667be3000c6aa29bac8a1e753dec3a7b
+ Error             : Can't find Sketch with that signature. Hash is invalid.
+===================================================================
[+] SketchCrapp last published date: 2020-11-01 serial 001

**macOS version [required]**
What is the macOS version?
Don't know how to find out? watch this https://support.apple.com/en-us/HT201260
Ex: macOS Catalina 10.15.7

**Sketch version [required]**
What is the Sketch version you want to patch?
Ex: 69 or any other version

**Terminal error message [required]**
Please copy the error message from the terminal if there has any.
SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... Error
[ERR] Can't find Sketch with that signature. Hash is invalid.
[INFO] Carefully review README file again
[INFO] If you still have problem copy the details below and open a new issue
[INFO] on GitHub repository: https://github.com/duraki/SketchCrapp
+===================================================================
+ Application Path  : /Applications/Sketch.app
+ Application Binary: /Applications/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : 69
+ Correct hash      : 2d4027890e2b72175c4a562f59c5d1adb2655b8c
+ Binary SHA1       : 85bc07b0667be3000c6aa29bac8a1e753dec3a7b
+ Error             : Can't find Sketch with that signature. Hash is invalid.
+===================================================================
[+] SketchCrapp last published date: 2020-11-01 serial 001

**Additional context [optional]**

**Screenshots [optional]** 
Add screenshots to help explain your problem.

**Comment by duraki** [comment]
Hi! 

Can you uninstall/remove Sketch.app from /Applications directory and then try this command in your Terminal:

`$ ./sketchcrapp.sh -m`

**Comment by elijahtsai** [comment]
Duplicated on #22 and #28.

**Comment by elijahtsai** [comment]
Hi @kirancornelio, 
Please reply to us about this suggestion ([link](https://github.com/duraki/SketchCrapp/issues/39#issuecomment-724537087)), otherwise we will close this issue when we released version 70.

**Comment by kirancornelio** [comment]
Dear Duraki/Sketchcrapp, It worked. Thank you for your support.

**Comment by elijahtsai** [comment]
It's very nice for us to hear your positive answer, thank you for trying our project. close issue.

**Comment by elijahtsai** [comment]
> Hi!
> 
> Can you uninstall/remove Sketch.app from /Applications directory and then try this command in your Terminal:
> 
> `$ ./sketchcrapp.sh -m`

@duraki , There is no need to remove the old app first before execute the command, the script will delete the old one before installing the new one.

**Comment by duraki** [comment]
Oh, thats cool to know! Thanks @elijahtsai didn't know that 😎
