### ISSUE TITLE
“Sketch” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by evasoek** [duraki/SketchCrapp#42]
**Describe the issue [required]**
I downloaded Sketch 69.2 and ran the script. When I try to open Sketch it says: “Sketch” is damaged and can’t be opened. You should move it to the Bin.

**macOS version [required]**
What is the macOS version?
MacOS Catalina 10.15.6

**Sketch version [required]**
What is the Sketch version you want to patch?
69.2

**Terminal error message [required]**
```
             __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai

SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 69.2 ... SketchCrapp starting ... OK
[+] Patching offsets for 69.2 ... Starting
[+] Patching address at offset: 0x5d09df with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000073 secs (13662 bytes/sec)
[+] Patching address at offset: 0x5d09e2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000030 secs (33288 bytes/sec)
[+] Patching address at offset: 0x5cf57e with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000030 secs (66576 bytes/sec)
[+] Patching address at offset: 0x5cf6ae with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000068 secs (14717 bytes/sec)
[+] SketchCrapp certificate already exists.
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
/Applications/Sketch.app: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Applications/Sketch.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Applications/Sketch.app/Contents/MacOS/sketchtool
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp process completed. Sketch.app has been patched :)
[+] -- Notice:
[+] If a dialogue shows up with message: “Sketch 3.app” can’t be opened
[+] please right-click the application and select open,
[+] or go to Settings -› Security and allow opening Sketch.app application.
[+]
[+] If you are using an old version and a dialogue shows up asking for password
[+] about "com.bohemiancoding.sketch3.HockeySDK"
[+] please enter your login password. Choose "Always Allow" to not be asked again.

[+] SketchCrapp (A Sketch.app cracking tool)
[+] https://github.com/duraki/SketchCrapp [by @duraki & @elijahtsai]
[+] SketchCrapp last published date: 2020-11-01 serial 001
```

**Comment by elijahtsai** [comment]
Hi, @evasoek According to the information you gave us, it seems like you missing some of essential tools, In order to fix this problem you need to download **Xcode** in the App Store, it's free😄. if the problem still troubles you, feel free to ask us again.

**Comment by duraki** [comment]
@evasoek instead of installing whole XCode bundle, might be easier to just pull Xcode CLI tools which will spare your drive disk memory. To do so, type this in your Terminal:


```
xcode-select --install
```

and follow the instructions on the screen.

Then use the magic function from SketchCrapp:

```
./sketchcrapp.sh -m
```

This will download and crack the latest Sketch version we support.

**Comment by elijahtsai** [comment]
@duraki ‘s answer is definitely nicer then mine, Cli is enough for current situation.

**Comment by evasoek** [comment]
@duraki @elijahtsai I installed the CLI and I think it worked now. The output was:

`           __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai

SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 69.2 ... SketchCrapp starting ... OK
[+] Patching offsets for 69.2 ... Starting
[+] Patching address at offset: 0x5d09df with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000041 secs (24385 bytes/sec)
[+] Patching address at offset: 0x5d09e2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000031 secs (32264 bytes/sec)
[+] Patching address at offset: 0x5cf57e with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000036 secs (55554 bytes/sec)
[+] Patching address at offset: 0x5cf6ae with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000030 secs (33288 bytes/sec)
[+] SketchCrapp certificate already exists.
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
/Applications/Sketch.app: replacing existing signature
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp process completed. Sketch.app has been patched :)
[+] -- Notice:
[+] If a dialogue shows up with message: “Sketch 3.app” can’t be opened
[+] please right-click the application and select open,
[+] or go to Settings -› Security and allow opening Sketch.app application.
[+]
[+] If you are using an old version and a dialogue shows up asking for password
[+] about "com.bohemiancoding.sketch3.HockeySDK"
[+] please enter your login password. Choose "Always Allow" to not be asked again.

[+] SketchCrapp (A Sketch.app cracking tool)
[+] https://github.com/duraki/SketchCrapp [by @duraki & @elijahtsai]
[+] SketchCrapp last published date: 2020-11-01 serial 001`

However when I open Sketch it still says: '1 day left' at the top right. Should that be there?

**Comment by elijahtsai** [comment]
Yes, if you don’t experience with license entry window pop-up, then that’s meaning everything is working, you can start whatever you want to create in Sketch, and remember to give us a ⭐️, it’s mean lot to us.

**Comment by evasoek** [comment]
Thanks! Definitely will give you guys a ⭐️. Well deserved, thanks for the support and great tool!

**Comment by joemartins** [comment]
Hello everyone. I'm facing exactly the same issue.
But, I think I may be doing something wrong.
I've already have CLI tools installed. This is the message I get when I try to install it:
`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

I've checked for Software Updates but my system is already up to date.

I'm targeting Sketch 69.2 version, but still I get this message:
![image](https://user-images.githubusercontent.com/5477498/101416833-64767980-38c9-11eb-912e-a9907ddb486a.png)

This is what appears when I run the Sketchcrapp script:
```
           __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai

SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 69.2 ... SketchCrapp starting ... OK
[+] Patching offsets for 69.2 ... Starting
[+] Patching address at offset: 0x5d09df with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000020 secs (49932 bytes/sec)
[+] Patching address at offset: 0x5d09e2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000013 secs (77672 bytes/sec)
[+] Patching address at offset: 0x5cf57e with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000017 secs (118149 bytes/sec)
[+] Patching address at offset: 0x5cf6ae with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000012 secs (83886 bytes/sec)
[+] SketchCrapp certificate already exists.
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
/Applications/Sketch.app: replacing existing signature
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
/Applications/Sketch.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Applications/Sketch.app/Contents/MacOS/sketchtool
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp process completed. Sketch.app has been patched :)
[+] -- Notice: 
[+] If a dialogue shows up with message: “Sketch 3.app” can’t be opened
[+] please right-click the application and select open, 
[+] or go to Settings -› Security and allow opening Sketch.app application.
[+] 
[+] If you are using an old version and a dialogue shows up asking for password
[+] about "com.bohemiancoding.sketch3.HockeySDK"
[+] please enter your login password. Choose "Always Allow" to not be asked again.

[+] SketchCrapp (A Sketch.app cracking tool)
[+] https://github.com/duraki/SketchCrapp [by @duraki & @elijahtsai]
[+] SketchCrapp last published date: 2020-11-01 serial 001

```

Is there anything I should be doing?
(sorry for the possible bad English. Not my native language).

Thanks in advance :)

**Comment by elijahtsai** [comment]
Hi @joemartins , I had transfer this issue to https://github.com/duraki/SketchCrapp/issues/43, because the question you asked is somehow not related. ☺️

**Comment by elijahtsai** [comment]
@evasoek , Thank you. Close #42.
