### ISSUE TITLE
Does not work on apple silicon.

### ISSUE THREAD

**Issue by aminroosta** [duraki/SketchCrapp#46]
Tested on an m1 macbook air, the bash script finishes successfully,
But the sketch app can not start and crashes with "Sketch exited unexpectedly" error.

Could it be that the new version has the native arm64 executable, and the crack corrupts it?

macOS: 11.0.1
Sketch: 70.3

**Comment by elijahtsai** [comment]
Yes, we had implemented, currently we are testing the script, stay toon for our next release.
P.S. This issue will close after next version of the script is release.

**Comment by duraki** [comment]
Really, we need to release latest patch 🎉 On NYE? WDYT 🍡

**Comment by elijahtsai** [comment]
@aminroosta Does the new version of the script solve your problem?

**Comment by aminroosta** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/2920178/103166105-c63b5b00-4859-11eb-99a4-4f5ea7dbf864.png">

@elijahtsai are you sure there is a new version? the last commit on master was Dec 21.

**Comment by elijahtsai** [comment]
yes...just run it and see if there have any problem.

**Comment by aminroosta** [comment]
Sketch fails to open.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/2920178/103169839-51c4e400-487a-11eb-82a0-61017c8b27be.png">

<details close>
<summary>Here is the log: </summary>
<br>

/Users/amin/projects/sketchcrapp $ ./sketchcrapp.sh
           __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai

SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 70.3 ... SketchCrapp starting ... OK
[+] Patching offsets for 70.3 ... Starting modern arch patch via bash&seek ...
[+] Patching address at offset: 0x58619f with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000017 secs (59075 bytes/sec)
[+] Patching address at offset: 0x5861a2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000007 secs (144631 bytes/sec)
[+] Patching address at offset: 0x584dee with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000010 secs (199729 bytes/sec)
[+] Patching address at offset: 0x584f1e with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000009 secs (113360 bytes/sec)
[+] Patching address at offset: 0x66d058 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000029 secs (519955 bytes/sec)
[+] Patching address at offset: 0x66d068 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000026 secs (500238 bytes/sec)
[+] Patching address at offset: 0xdcd574 with value: \01
1+0 records in
1+0 records out
1 bytes transferred in 0.000008 secs (123362 bytes/sec)
[+] Patching address at offset: 0xdcd578 with value: \24
1+0 records in
1+0 records out
1 bytes transferred in 0.000007 secs (144631 bytes/sec)
[+] Patching address at offset: 0xdcc1c1 with value: \65\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000007 secs (289262 bytes/sec)
[+] Patching address at offset: 0xdcc30c with value: \64
1+0 records in
1+0 records out
1 bytes transferred in 0.000005 secs (199729 bytes/sec)
[+] Patching address at offset: 0xed0fd7 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000026 secs (577198 bytes/sec)
[+] Patching address at offset: 0xed0fe7 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000023 secs (562123 bytes/sec)
[+] SketchCrapp certificate already exists.
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
/Applications/Sketch.app: replacing existing signature
/Applications/Sketch.app: the codesign_allocate helper tool cannot be found or used
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp process completed. Sketch.app has been patched :)
[+] -- Notice:
[+] If a dialogue shows up with message: “Sketch 3.app” can’t be opened
[+] please right-click the application and select open,
[+] or go to Settings -› Security and allow opening Sketch.app application.
[+]
[+] If you are using an old version and a dialogue shows up asking for password
[+] about "com.bohemiancoding.sketch3.HockeySDK"
[+] please enter your login password. Choose "Always Allow" to not be asked again.

[+] SketchCrapp (A Sketch.app cracking tool)
[+] https://github.com/duraki/SketchCrapp [by @duraki & @elijahtsai]
[+] SketchCrapp last published date: 2020-12-27 serial 001

</details>

**Comment by elijahtsai** [comment]
https://github.com/duraki/SketchCrapp/issues/42#issuecomment-738634634
Use this method to install necessary tools

**Comment by aminroosta** [comment]
I had xcode installed, then tried
```
./sketchcrapp.sh -m
```

Still fails, 

<details close>
<summary>Here is the log: </summary>
<br>

./sketchcrapp.sh -m
           __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai

[+] Checking directory tmp existence ... OK
[+] Fetching https://download.sketch.com/sketch-70.3-109109.zip ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 58.5M  100 58.5M    0     0  14.7M      0  0:00:03  0:00:03 --:--:-- 14.7M
Checking if Sketch.app exist in /tmp ... Not exist. Continuous.
[+] Checking if Sketch.app exist in /Applications ... Not exist. Continuous.
[+] Moving Sketch.app to /Applications directory ... Successfully.
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 70.3 ... SketchCrapp starting ... OK
[+] Patching offsets for 70.3 ... Starting modern arch patch via bash&seek ...
[+] Patching address at offset: 0x58619f with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000012 secs (83886 bytes/sec)
[+] Patching address at offset: 0x5861a2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000006 secs (161319 bytes/sec)
[+] Patching address at offset: 0x584dee with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000009 secs (220753 bytes/sec)
[+] Patching address at offset: 0x584f1e with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000006 secs (167772 bytes/sec)
[+] Patching address at offset: 0x66d058 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000025 secs (599186 bytes/sec)
[+] Patching address at offset: 0x66d068 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000021 secs (619613 bytes/sec)
[+] Patching address at offset: 0xdcd574 with value: \01
1+0 records in
1+0 records out
1 bytes transferred in 0.000005 secs (199729 bytes/sec)
[+] Patching address at offset: 0xdcd578 with value: \24
1+0 records in
1+0 records out
1 bytes transferred in 0.000004 secs (262144 bytes/sec)
[+] Patching address at offset: 0xdcc1c1 with value: \65\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000009 secs (220753 bytes/sec)
[+] Patching address at offset: 0xdcc30c with value: \64
1+0 records in
1+0 records out
1 bytes transferred in 0.000007 secs (139810 bytes/sec)
[+] Patching address at offset: 0xed0fd7 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000029 secs (515693 bytes/sec)
[+] Patching address at offset: 0xed0fe7 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000027 secs (478298 bytes/sec)
[+] SketchCrapp certificate already exists.
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
/Applications/Sketch.app: replacing existing signature
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp process completed. Sketch.app has been patched :)
[+] -- Notice:
[+] If a dialogue shows up with message: “Sketch 3.app” can’t be opened
[+] please right-click the application and select open,
[+] or go to Settings -› Security and allow opening Sketch.app application.
[+]
[+] If you are using an old version and a dialogue shows up asking for password
[+] about "com.bohemiancoding.sketch3.HockeySDK"
[+] please enter your login password. Choose "Always Allow" to not be asked again.

[+] SketchCrapp (A Sketch.app cracking tool)
[+] https://github.com/duraki/SketchCrapp [by @duraki & @elijahtsai]
[+] SketchCrapp last published date: 2020-12-27 serial 001

</details>

**Comment by elijahtsai** [comment]
I'll leave this issue open. Because currently, we don't have an Apple Silicon Mac machine to test the arm64 architecture app. All the arm64 architecture patch code in the script will be removed after this post and I will add a notice in README with this problem. With that said our script only supports Intel-based of mac machines.

**Comment by aminroosta** [comment]
Noted, thanks @elijahtsai

**Comment by elijahtsai** [comment]
@aminroosta We've update info in the Notice section of README file, take a look at it. I sure it can help you out.

**Comment by elijahtsai** [comment]
Hello, @aminroosta , we've updated our script!! please re-download our script again, and patch it with the command `./sketchcrapp -m` and tell us your result!!

P.S. This issue will tide with issue #51 , so if #51 closed this issue will be close at the same time.
