### ISSUE TITLE
We are looking for Apple silicon testers

### ISSUE THREAD

**Issue by duraki** [duraki/SketchCrapp#51]
~ we are looking for testers who would like to contribute in open-source development of SketchCrapp. If you are using Apple silicon Mac-based PCs (post-2020), let us know below how does SketchCrapp behave and does Sketch works all right. Any quirks or bugs? Some feature is missing? Write a comment below.

> Currently, the script can only patch with the Intel-based of Mac machines. But lucky for the apple silicon user you can use Rosetta 2 to get the job done.

See Rosetta 2 for reference:

* https://support.apple.com/en-us/HT211861

**Comment by JosephShenton** [comment]
I will gladly test, I just tried using it and it worked except for Sketch now asking for my apple username and password because apparently it was downloaded on another computer and when I provide my apple id it does nothing.
<img width="609" alt="Screen Shot 2021-01-08 at 8 38 40 pm" src="https://user-images.githubusercontent.com/12966231/103999816-7f524b80-51f1-11eb-9c4d-2e97254e19d4.png">
<img width="698" alt="Screen Shot 2021-01-08 at 8 37 26 pm" src="https://user-images.githubusercontent.com/12966231/103999835-85e0c300-51f1-11eb-87ff-a3747bea93d2.png">

**Comment by duraki** [comment]
Can you remove Sketch completely and then try SketchCrapp via a magic function:

ie. `sh sketchcrapp.sh -m`

**Comment by JosephShenton** [comment]
Hey! Yes, I have done that and I get the same issue.

**Comment by elijahtsai** [comment]
We need entire (1)terminal message in order to understand how it work in your computer, second, (2)what issue you are facing? Describe more detail to us, there has more chance the problem can be fix. (3)Like what step you do...etc and I don’t understand why there will have Apple ID request, (4)are you still get the Apple ID login request second time the command Duraki told you to do?

**Comment by elijahtsai** [comment]
Btw  @JosephShenton thanks you for join us, to let us having the chance the make our project SketchCrapp more powerful!!!!

**Comment by duraki** [comment]
~offtopic: added @JosephShenton as a collaborator =) Welcome

**Comment by JosephShenton** [comment]
Hey! I am currently writing this from my phone but the terminal output from my reading showed no errors, however when I get home from work I will send it. 

Steps I took:
Downloaded Sketch from the official website, put it in my applications folder.
Downloaded SketchCrapp, and ran ./sketchcrapp.sh 
Opened Sketch from Applications Folder
Sketch bounces on dock a few times then dies
Then about 30 seconds later a popup shows and says "This app was downloaded on on another computer, please enter the apple id used to download this app" 
So I enter my Apple ID and it just does nothing.

So I deleted sketch from my applications folder, redownloaded, put in applications folder, opened it and it ran normally without the crack

So I deleted sketch again and run ./SketchCrapp.sh -m
Again, I didn't see any errors but upon completion and opening sketch it did the apple id prompt again

**Comment by elijahtsai** [comment]
Hi, @JosephShenton We are waiting for your terminal output, and since we had released the patch script of the latest version currently having, so I will get back to this problem and more focus on this after there has a new version coming. 💪🏻

**Comment by JosephShenton** [comment]
Hey, sorry for the delay! Here it is

josephshenton@Mac-mini sketchcrapp % cd $HOME/sketchcrapp && ./sketchcrapp.sh -m
           __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai

[+] Checking directory tmp existence ... OK
[+] Fetching https://download.sketch.com/sketch-70.3-109109.zip ... 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 58.5M    1 1039k    0     0   146k      0  0:06:50  0:00:07  0:06:43  159k
100 58.5M  100 58.5M    0     0   132k      0  0:07:33  0:07:33 --:--:--  161k
Checking if Sketch.app exist in /tmp ... Not exist. Continuous.
[+] Checking if Sketch.app exist in /Applications ... Exist. Removing.
[+] Moving Sketch.app to /Applications directory ... Successfully.
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 70.3 ... SketchCrapp starting ... OK
[+] Patching offsets for 70.3 ... Starting modern arch patch via bash&seek ...
[+] Patching address at offset: 0x58619f with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000011 secs (91181 bytes/sec)
[+] Patching address at offset: 0x5861a2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000005 secs (199729 bytes/sec)
[+] Patching address at offset: 0x584dee with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000007 secs (289262 bytes/sec)
[+] Patching address at offset: 0x584f1e with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000005 secs (209715 bytes/sec)
[+] Patching address at offset: 0x66d058 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000024 secs (629146 bytes/sec)
[+] Patching address at offset: 0x66d068 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000021 secs (619613 bytes/sec)
[+] SketchCrapp certificate already exists.
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
/Applications/Sketch.app: replacing existing signature
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp process completed. Sketch.app has been patched :)
[+] -- Notice: 
[+] If a dialogue shows up with message: “Sketch 3.app” can’t be opened
[+] please right-click the application and select open, 
[+] or go to Settings -› Security and allow opening Sketch.app application.
[+] 
[+] If you are using an old version and a dialogue shows up asking for password
[+] about "com.bohemiancoding.sketch3.HockeySDK"
[+] please enter your login password. Choose "Always Allow" to not be asked again.

[+] SketchCrapp (A Sketch.app cracking tool)
[+] https://github.com/duraki/SketchCrapp [by @duraki & @elijahtsai]
[+] SketchCrapp last published date: 2020-12-28 serial 001

**Comment by Aurther-Nadeem** [comment]
Hey, M1 MacBook user here. Having the same issue, happy to help :)

**Comment by elijahtsai** [comment]
Hi, @Aurther-Nadeem welcome to this community 🥳🥳🥳

**Comment by elijahtsai** [comment]
@Aurther-Nadeem have you tried to used this method yet? https://support.apple.com/en-us/HT211861
P.S. Please follow the instructions strictly, and do not open the application before step four, also please inform us about the other situation or step we don’t write down below.  

Step one: remove any Sketch application from your computer 💻 
Step two: launch script with `./sketchcrapp.sh -m`
Step three: right click application and choose **Get info**, after window pop up, choose **Open using Rosetta**
Step four: open the application!!

**Comment by elijahtsai** [comment]
To: @JosephShenton , @Aurther-Nadeem 
cc: @duraki 

Hello👋🏻, our good fans, I've fixed some bugs in the script. please redownload the script and patch with the command `./sketchcrapp.sh -m` , and get back some msg to us. thank you!🥳

**Comment by Aurther-Nadeem** [comment]
Yay! It's working on the M1 MacBook Pro :)

**Comment by JosephShenton** [comment]
Awesome! It is working now on the M1 Mac Mini!

**Comment by elijahtsai** [comment]
@Aurther-Nadeem: Thank you for testing but can you give me some screenshots, I need the terminal message, application document window, license window, and application get info window(**with all triangle open**). following images are for the example.
P.S. you should remove all your personal information before uploading.😉

**terminal image:**
<img width="1282" alt="Screenshot 2021-01-16 at 12 14 48" src="https://user-images.githubusercontent.com/42165051/104796887-16706200-57f5-11eb-8fe7-ea150316fc20.png">
**application document window:**
<img width="1258" alt="Screenshot 2021-01-16 at 12 14 10" src="https://user-images.githubusercontent.com/42165051/104796906-41f34c80-57f5-11eb-9f4b-498949c11e4d.png">
**license window**
<img width="632" alt="Screenshot 2021-01-16 at 12 14 14" src="https://user-images.githubusercontent.com/42165051/104796912-4cade180-57f5-11eb-9473-d2fca1533520.png">
<img width="632" alt="Screenshot 2021-01-16 at 12 14 17" src="https://user-images.githubusercontent.com/42165051/104796915-4f103b80-57f5-11eb-83d0-0ada534511a4.png">
**application get info window**
<img width="377" alt="Screenshot 2021-01-16 at 12 15 12" src="https://user-images.githubusercontent.com/42165051/104796923-5e8f8480-57f5-11eb-91bd-d4ae010f3953.png">

**Comment by Aurther-Nadeem** [comment]
Sure thing!
<img width="1550" alt="Screenshot 2021-01-16 at 04 24 39" src="https://user-images.githubusercontent.com/49573040/104797071-46971100-57b3-11eb-933c-b540aeeea3ba.png">
<img width="1550" alt="Screenshot 2021-01-16 at 04 24 44" src="https://user-images.githubusercontent.com/49573040/104797062-40a13000-57b3-11eb-8a98-493db3130cab.png">
<img width="377" alt="Screenshot 2021-01-16 at 04 25 49 1" src="https://user-images.githubusercontent.com/49573040/104797066-4434b700-57b3-11eb-9917-7bcd8f89a686.png">
<img width="632" alt="Screenshot 2021-01-16 at 04 25 25" src="https://user-images.githubusercontent.com/49573040/104797067-4565e400-57b3-11eb-9436-e3e5e5b8644a.png">
<img width="632" alt="Screenshot 2021-01-16 at 04 25 22" src="https://user-images.githubusercontent.com/49573040/104797069-4565e400-57b3-11eb-9490-5d2e7a5b63d2.png">
<img width="1552" alt="Screenshot 2021-01-16 at 04 25 07" src="https://user-images.githubusercontent.com/49573040/104797070-45fe7a80-57b3-11eb-909e-5b76e836f768.png">

**Comment by elijahtsai** [comment]
Yes!!!, Thank you @Aurther-Nadeem

**Comment by elijahtsai** [comment]
What about @JosephShenton ??😃

**Comment by JosephShenton** [comment]
<img width="690" alt="Screen Shot 2021-01-16 at 6 24 30 pm" src="https://user-images.githubusercontent.com/12966231/104806002-500e9080-5828-11eb-8f1e-300deb62dbfa.png">
<img width="377" alt="Screen Shot 2021-01-16 at 6 25 10 pm" src="https://user-images.githubusercontent.com/12966231/104806011-661c5100-5828-11eb-89dd-fc84f41e8d78.png">
<img width="1392" alt="Screen Shot 2021-01-16 at 6 25 30 pm" src="https://user-images.githubusercontent.com/12966231/104806013-6fa5b900-5828-11eb-875a-b89c23d47c92.png">
<img width="632" alt="Screen Shot 2021-01-16 at 6 25 43 pm" src="https://user-images.githubusercontent.com/12966231/104806014-759b9a00-5828-11eb-9fac-21bc80d256ce.png">
<img width="632" alt="Screen Shot 2021-01-16 at 6 25 45 pm" src="https://user-images.githubusercontent.com/12966231/104806015-7a604e00-5828-11eb-99fb-32df767233a3.png">

**Comment by elijahtsai** [comment]
Thank you @JosephShenton , it’s meaning lot to me and @duraki , if you gentlemen don’t mind , we can keep working together, for the future version 💪🏻

**Comment by elijahtsai** [comment]
I will clean the code and renew readme file, then we can close this issue.

**Comment by elijahtsai** [comment]
To: @JosephShenton , @Aurther-Nadeem 

Thank you for your testing, We've your names in the [README.md](https://github.com/duraki/SketchCrapp) file, you can go check it out!! 👍🏻🥳❤️

**Comment by duraki** [comment]
This was spot-on iteration guys. xD
