### ISSUE TITLE
Full walkthrough Please

### ISSUE THREAD

**Issue by Sambirdy** [duraki/SketchCrapp#6]
Hi, 

I am completely new to the coding side of things and was hoping you could please provide a full walkthrough for someone who has no clue about coding and GitHub. Sorry to cause any inconvenience. 

Thanks Again

**Comment by elijahtsai** [comment]
What part of the walkthrough do you need? The readme for how to use the script is somehow not clear for you? or the blog @duraki wrote you got any question?

**Comment by Sambirdy** [comment]
The readme for how to use the script. How do I make the script executable?

**Comment by duraki** [comment]
Just copy and paste the 3 commands given in the README in your terminal and it should work without the fuss:

https://github.com/duraki/SketchCrapp#usage
