### ISSUE TITLE
New sketch version 70.5

### ISSUE THREAD

**Issue by rottenpants466** [duraki/SketchCrapp#60]
**Sketch version [required]**
What is the Sketch version you want support for?
Ex: 70.5

**Additional context [optional]**
A new version came out :)

**Comment by elijahtsai** [comment]
Okay! thank you for notify us. we will update ASAP! 👍🏻

**Comment by elijahtsai** [comment]
I added v70.5 args!! This issue will be closed if #61 is merged.

**Comment by rottenpants466** [comment]
much love 👍🏻
