### ISSUE TITLE
Can't find Sketch with that signature. Hash is invalid.

### ISSUE THREAD

**Issue by juliamartijmg** [duraki/SketchCrapp#65]
**Describe the request [required]**
I'm getting this error: 
If you could help me with that I'd really appreciate it :)

+===================================================================
+ Application Path  : /Applications/Sketch.app
+ Application Binary: /Applications/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : 63
+ Correct hash      : Input version string invaild, cannot lookup correct hash value.
+ Binary SHA1       : 5508080ea094f92b21b1cf3cb0b612c5d39d18db
+ Error             : Can't find Sketch with that signature. Hash is invalid.
+===================================================================

macOS version
macOS High Sierra 10.13.6

**Sketch version [required]**
v63

**Additional context [optional]**
Full output:
Last login: Tue Mar  2 09:58:36 on ttys000
MacBook-Pro-4:~ juliamartigomez$ cd $HOME && git clone https://github.com/duraki/SketchCrapp
fatal: destination path 'SketchCrapp' already exists and is not an empty directory.
MacBook-Pro-4:~ juliamartigomez$ cd $HOME/SketchCrapp && chmod +x sketchcrapp.sh
MacBook-Pro-4:SketchCrapp juliamartigomez$ cd $HOME/SketchCrapp && ./sketchcrapp.sh
           __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai

SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
./sketchcrapp.sh: line 443: [: : integer expression expected
[+] Validating executable file ... Error
[ERR] Can't find Sketch with that signature. Hash is invalid.
[INFO] Carefully review README file again
[INFO] If you still have problem copy the details below and open a new issue
[INFO] on GitHub repository: https://github.com/duraki/SketchCrapp
+===================================================================
+ Application Path  : /Applications/Sketch.app
+ Application Binary: /Applications/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : 63
+ Correct hash      : Input version string invaild, cannot lookup correct hash value.
+ Binary SHA1       : 5508080ea094f92b21b1cf3cb0b612c5d39d18db
+ Error             : Can't find Sketch with that signature. Hash is invalid.
+===================================================================
[+] SketchCrapp last published date: 2021-02-25 serial 001
MacBook-Pro-4:SketchCrapp juliamartigomez$

**Comment by p-nicolaou** [comment]
I was about to open the same ticket 😅
I tried restarting my computer first, no luck. It used to work on 70.4.

**Comment by p-nicolaou** [comment]
This is me trying the proposed PR version of the script. Still, no luck.
```
pnikolaou@192 SketchCrapp % cd $HOME/SketchCrapp && ./sketchcrapp.sh
           __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai
SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 70.6 ... SketchCrapp starting ... OK
[+] Patching offsets for 70.6 ... Starting modern arch patch via bash&seek ...
[+] Patching address at offset: 0x585eef with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000029 secs (34380 bytes/sec)
[+] Patching address at offset: 0x585ef2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000035 secs (28533 bytes/sec)
[+] Patching address at offset: 0x584b3e with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000028 secs (71698 bytes/sec)
[+] Patching address at offset: 0x584c6e with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000023 secs (43240 bytes/sec)
[+] Patching address at offset: 0x66ce63 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000080 secs (187805 bytes/sec)
[+] Patching address at offset: 0x66ce73 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000071 secs (182973 bytes/sec)
[+] Patching address at offset: 0xdcd404 with value: \01
1+0 records in
1+0 records out
1 bytes transferred in 0.000061 secs (16448 bytes/sec)
[+] Patching address at offset: 0xdcd408 with value: \24
1+0 records in
1+0 records out
1 bytes transferred in 0.000024 secs (41528 bytes/sec)
[+] Patching address at offset: 0xdcc07c with value: \165\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000027 secs (74235 bytes/sec)
[+] Patching address at offset: 0xdcc19f with value: \64
1+0 records in
1+0 records out
1 bytes transferred in 0.000023 secs (43240 bytes/sec)
[+] Patching address at offset: 0xed0fbc with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000078 secs (192399 bytes/sec)
[+] Patching address at offset: 0xed0fcc with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000070 secs (185462 bytes/sec)
[+] Checking user default keychain ... Exist.
[+] SketchCrapp certificate already exists.
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
sketchcrapp: no identity found
[-] Failed to signing Sketch bundle.
[+] Starting fixing process.
[+] Remove identity.
security: SecTrustSettingsRemoveTrustSettings (user): No Trust Settings were found.
[-] Unable to delete sketchcrapp identity.
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp last published date: 2021-02-27 serial 001
pnikolaou@192 SketchCrapp % 
```

**Comment by elijahtsai** [comment]
@juliamartijmg , please check the supported version in the readme file, we don’t support v63, but we do supported v63.1, you can check the update log to see the compatibility, if you really need us to support v63 , you need to give us a reason, like the project you working on is really need to run in v63, and we will decide if we will support it or not

**Comment by elijahtsai** [comment]
If this issue does not get any reply before 2021-03-08 00:00:00 will be treat as Not Important and close by us. if you still having a question, you may need to open another one.
