### ISSUE TITLE
After updating to latest version, I can't launch Sketch anymore

### ISSUE THREAD

**Issue by p-nicolaou** [duraki/SketchCrapp#66]
Moving my comment to its own issue ticket.

The last usable version was 70.4. I was able to patch and run with no problem. Yesterday, I've tried 70.6 but for some reason is failing to sign the bundle. Even reverting back to 70.4 didn't fix the issue.

I deleted are references to `sketchcrapp` from keychain. No luck either.

This is me trying the proposed PR version of the script. Still, no luck.
```
pnikolaou@192 SketchCrapp % cd $HOME/SketchCrapp && ./sketchcrapp.sh
           __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai
SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 70.6 ... SketchCrapp starting ... OK
[+] Patching offsets for 70.6 ... Starting modern arch patch via bash&seek ...
[+] Patching address at offset: 0x585eef with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000029 secs (34380 bytes/sec)
[+] Patching address at offset: 0x585ef2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000035 secs (28533 bytes/sec)
[+] Patching address at offset: 0x584b3e with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000028 secs (71698 bytes/sec)
[+] Patching address at offset: 0x584c6e with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000023 secs (43240 bytes/sec)
[+] Patching address at offset: 0x66ce63 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000080 secs (187805 bytes/sec)
[+] Patching address at offset: 0x66ce73 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000071 secs (182973 bytes/sec)
[+] Patching address at offset: 0xdcd404 with value: \01
1+0 records in
1+0 records out
1 bytes transferred in 0.000061 secs (16448 bytes/sec)
[+] Patching address at offset: 0xdcd408 with value: \24
1+0 records in
1+0 records out
1 bytes transferred in 0.000024 secs (41528 bytes/sec)
[+] Patching address at offset: 0xdcc07c with value: \165\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000027 secs (74235 bytes/sec)
[+] Patching address at offset: 0xdcc19f with value: \64
1+0 records in
1+0 records out
1 bytes transferred in 0.000023 secs (43240 bytes/sec)
[+] Patching address at offset: 0xed0fbc with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000078 secs (192399 bytes/sec)
[+] Patching address at offset: 0xed0fcc with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000070 secs (185462 bytes/sec)
[+] Checking user default keychain ... Exist.
[+] SketchCrapp certificate already exists.
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
sketchcrapp: no identity found
[-] Failed to signing Sketch bundle.
[+] Starting fixing process.
[+] Remove identity.
security: SecTrustSettingsRemoveTrustSettings (user): No Trust Settings were found.
[-] Unable to delete sketchcrapp identity.
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp last published date: 2021-02-27 serial 001
pnikolaou@192 SketchCrapp % 
```

_Originally posted by @p-nicolaou in https://github.com/duraki/SketchCrapp/issues/65#issuecomment-788771709_

**Comment by p-nicolaou** [comment]
<img width="264" alt="Screenshot 2021-03-03 at 09 13 15" src="https://user-images.githubusercontent.com/17762810/109767787-c0b71400-7c00-11eb-87c7-5e9cb4d0e3a4.png">
Attempting to launch Sketch ..

**Comment by elijahtsai** [comment]
I’m still figuring how this problem happened, and is this problem only in m1 or both

**Comment by p-nicolaou** [comment]
<img width="587" alt="Screenshot 2021-03-03 at 11 48 46" src="https://user-images.githubusercontent.com/17762810/109786994-6fb21a80-7c16-11eb-9b48-2d3ffb75127d.png">
This is my setup

**Comment by p-nicolaou** [comment]
<img width="587" alt="Screenshot 2021-03-03 at 11 48 46" src="https://user-images.githubusercontent.com/17762810/109787234-aee06b80-7c16-11eb-89a9-f71a32cb8a2a.png">
This is my setup

**Comment by p-nicolaou** [comment]
Just tried the 68.2 Sketch borrowing the `sketchcrapp.sh` from a colleague of mine who didn't update for a long time. Surprisingly, it works like gem. Still, no idea what the issue was but if you want me to try something out, let me know

**Comment by elijahtsai** [comment]
Hi, @p-nicolaou  I’ll suggest you delete our certificate and let it re-generate again, open the keychain app, and at the top-right corner search “sketchcrapp”, in the result list delete the file match identical with “sketchcrapp” (normally it will have two files one for certificate one for private key), and run the script again see if this help

**Comment by p-nicolaou** [comment]
@elijahtsai I've tried that already with no luck. It re-generated certificate and private key but can't sign Sketch.

**Comment by elijahtsai** [comment]
Hi, @p-nicolaou , Sorry for my mistake, I know what goes wrong, now the script should be working, try to redownload the script again and patch your bundle sees if the problem is solved.

**Comment by p-nicolaou** [comment]
@elijahtsai thank you for the quick fix. All sorted now!! I am able to install the latest Sketch once again 😄

**Comment by elijahtsai** [comment]
Nice, good to know the script is working for you, have a nice day!🥳
