### ISSUE TITLE
MacOS 10.13.6 with Sketch 63.1 ?

### ISSUE THREAD

**Issue by marcspin** [duraki/SketchCrapp#68]
Any chance of a version that could work on a MacOS High Sierra 10.13.6 with Sketch 63.1?

Currently, if I try to use SketchCrapp I get the following:

cd $HOME && git clone https://github.com/duraki/SketchCrapp
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Thank you

**Comment by elijahtsai** [comment]
@marcspin you need to install Xcode command-line package first, open your terminal app and type `xcode-select --install`

**Comment by elijahtsai** [comment]
Check our previous asked answer 
https://github.com/duraki/SketchCrapp/issues/42#issuecomment-738634634

**Comment by marcspin** [comment]
That’s brilliant, thank you! Sketch still tells me I only have 5 days left, but I am assuming I can just ignore that, right?
Thank you.

**Comment by elijahtsai** [comment]
Essentially, if you can see our name tag at top-right corner, you are good. 
It’s good to hear the script is working for you, have a nice day. 🥳
Close #68
