### ISSUE TITLE
Doesn`t works for me

### ISSUE THREAD

**Issue by Shiloasi** [duraki/SketchCrapp#7]
Hi guys,
I get this error:
+===================================================================
+ Issue details ‹s:sketchcrapp›
+ Application Path  : /Applications/Sketch.app
+ Application Binary: /Applications/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : ‹nil›
+ Binary SHA1       : 4128ac5c9df230a8756a246cf51db134d4f4d28b
+ Error             : binaryerr››
+===================================================================

**Comment by elijahtsai** [comment]
Hi @Shiloasi, please make sure your sketch application is **clean** by clean I mean directly downloaded from sketch, unzipped and make sure without any additional modification before patch, also please tell us your sketch version and your macOS version, if don’t know how to find out watch this: https://support.apple.com/en-us/HT201260

**Comment by Shiloasi** [comment]
Thanks, it works!
