### ISSUE TITLE
Missing xcrun 

### ISSUE THREAD

**Issue by Suriv** [duraki/SketchCrapp#70]
**Describe the issue [required]**
70.6 Fail
**macOS version [required]**
What is the macOS version?
macOS Catalina 10.15.6

**Sketch version [required]**
What is the Sketch version you want to patch?
70.6

**Terminal error message [required]**

[+] Checking directory tmp existence ... OK
[+] Fetching https://download.sketch.com/sketch-70.6-109241.zip ... 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 58.5M  100 58.5M    0     0  10.2M      0  0:00:05  0:00:05 --:--:-- 10.5M
[+] Checking if Sketch.app exist in /tmp ... Not exist. Continuous.
[+] Checking if Sketch.app exist in /Applications ... Exist. Removing.
[+] Moving Sketch.app to /Applications directory ... Successfully.
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 70.6 ... SketchCrapp starting ... OK
[+] Patching offsets for 70.6 ... Starting modern arch patch via bash&seek ...
[+] Patching address at offset: 0x585eef with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000033 secs (30175 bytes/sec)
[+] Patching address at offset: 0x585ef2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000028 secs (35545 bytes/sec)
[+] Patching address at offset: 0x584b3e with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000031 secs (64528 bytes/sec)
[+] Patching address at offset: 0x584c6e with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000023 secs (43691 bytes/sec)
[+] Patching address at offset: 0x66ce63 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000079 secs (190074 bytes/sec)
[+] Patching address at offset: 0x66ce73 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000124 secs (104858 bytes/sec)
[+] Patching address at offset: 0xdcd404 with value: \01
1+0 records in
1+0 records out
1 bytes transferred in 0.000028 secs (35545 bytes/sec)
[+] Patching address at offset: 0xdcd408 with value: \24
1+0 records in
1+0 records out
1 bytes transferred in 0.000035 secs (28533 bytes/sec)
[+] Patching address at offset: 0xdcc07c with value: \165\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000045 secs (44384 bytes/sec)
[+] Patching address at offset: 0xdcc19f with value: \64
1+0 records in
1+0 records out
1 bytes transferred in 0.000046 secs (21845 bytes/sec)
[+] Patching address at offset: 0xed0fbc with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000082 secs (182891 bytes/sec)
[+] Patching address at offset: 0xed0fcc with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000069 secs (188671 bytes/sec)
[+] Checking user default keychain ... Exist
[+] Checking SketchCrapp identity ... Exist
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
/Applications/Sketch.app: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Applications/Sketch.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Applications/Sketch.app/Contents/MacOS/sketchtool
[-] Failed to sign Sketch bundle.
[+] Automatic fix process started.
[+] Removing certificate ...
[+] Re-creating signature identity ...
[+] Generating self-signed certificate ...
Generating a 521 bit EC private key
writing new private key to 'pk.pem'
-----
[+] Creating pkcs package...
[+] Re-importing signature identity ...
[+] Importing private key and self-signed certificate
1 identity imported.
[+] Resigning application bundle again using signature identity ...
/Applications/Sketch.app: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Applications/Sketch.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Applications/Sketch.app/Contents/MacOS/sketchtool
[-] Failed to sign Sketch bundle. Automatic method failed.
[INFO] Copy the full log and open a new issue on GitHub repository: https://github.com/duraki/SketchCrapp
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp last published date: 2021-03-07 serial 005

**Comment by ZoeyWoohoo** [comment]
@Suriv Install the Xcode toolkit should simply work. (Ref: [missing xcrun](https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/))

> $ xcode-select --install

**Comment by elijahtsai** [comment]
Duplicate #68

**Comment by elijahtsai** [comment]
Thank you @ZoeyWoohoo

**Comment by elijahtsai** [comment]
Answer: https://github.com/duraki/SketchCrapp/issues/70#issuecomment-797214408

**Comment by duraki** [comment]
Just saw @ZoeyWoohoo was responding to help random user. Thats nice to see. A supporter of that kind is rarely seen on GitHub these days. 👋😊

**Comment by elijahtsai** [comment]
Thumbs up 👍🏻
