### ISSUE TITLE
not working for Sketch 70.

### ISSUE THREAD

**Issue by daliborristic883** [duraki/SketchCrapp#71]
SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[ERR] Version 70 is not supported, please carefully review README file again.
[INFO] Copy the details below and open a new issue on GitHub repository: https://github.com/duraki/SketchCrapp
+===================================================================
+ Issue details ‹s:sketchcrapp›
+ Application Path  : /Applications/Sketch.app
+ Application Binary: /Applications/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : 70
+ Binary SHA1       : 64dc3eb2b1da130a56ff0903f9ec46d050d236c1
+ Error             : Version 70 is not supported.
+===================================================================
[+] SketchCrapp last published date: 2021-03-07 serial 005

**Comment by elijahtsai** [comment]
Yes, we don’t support version 70, you can try out 70.2 or later.
