### ISSUE TITLE
Ghidra analyse settings

### ISSUE THREAD

**Issue by icedice** [duraki/SketchCrapp#76]
Could you please share your Ghidra analyse settings, it would be extremely helpfull to me.  When trying to follow the tutorial i get a lot of "bald spots" in Ghidra, including addresses that I need to patch. I'm working on Sketch v63.1 like the tutorial. 
I need to patch 0x1004a1738 but in my list view it looks like this:

`1004a1738 0f             ??        0Fh`

I used default settings for Ghidra analyse and I suspect that I need to tweak the settings.

**Comment by elijahtsai** [comment]
Try to re-decompile your binary file by using D shortcut key or select decompile in the menu. I’ve same problem as yours , thats how I fix it. 😂

**Comment by icedice** [comment]
It worked! Thanks!
