### ISSUE TITLE
Doesn't work on 67.1 or 67.2

### ISSUE THREAD

**Issue by kuthulhu** [duraki/SketchCrapp#8]
I am getting no error after script run. App works normally after script. But I still get "x Days Left - Register Now" on right corner in any document and counts down each day as before. It is like script did nothing.

I uninstall currently installed version, downloaded new one from sketch website. Deleted keychain entries before each install. Tried both 67.1 and 67.2. Tried "sudo ./sketchcrapp". Is there anything else I can do?

**Comment by elijahtsai** [comment]
Hi @kuthulhu, If you successfully patched the "Register Now" label you got is normal, you can ignore it. the only problem is that after trial day over will you get Register license window pop-up? If not then we good, If yes then we may discuss even more on this problem. No matter the answer is yes or no please tell us the result. Thanks.

**Comment by duraki** [comment]
It's normal to see that. The patch is directly related to binary offsets for checking number of days on backend side, but not for visible UIView//UILabel related to presentation model. We will add this to README. We might fix it in the future :)

**Comment by duraki** [comment]
We will continue to track this change in separate issue at #11-.
