### ISSUE TITLE
[-] Failed to sign Sketch bundle. missing xcrun

### ISSUE THREAD

**Issue by claudiabgz** [duraki/SketchCrapp#82]
This is the log that appeared and did not work. Thank you.

cd $HOME/SketchCrapp && ./sketchcrapp.sh 
           __       __      __
      ___ / /_____ / /_____/ /  ___________ ____  ___
    ( _-</  '_/ -_) __/ __/ _ \/ __/ __/ _ `/ _ \/ _ \
    /___/_/\_\\__/\__/\__/_//_/\__/_/  \_,_/ .__/ .__/
                                          /_/  /_/
         Sketch.App Patch Tool (https://github.com/duraki/SketchCrapp)
         by @duraki & @elijahtsai

SketchCrapp is finding application bundle path ...
[+] Selected Sketch.app path is </Applications> (auto-detected) ... OK
[+] Analysing application bundle ... Starting
[+] Finding executable file ... OK
[+] Finding Info.plist ... OK
[+] Checking Info.plist for CFBundleShortVersionString ... OK
[+] Validating executable file ... OK
[+] Selected Sketch.app version is 71.2 ... SketchCrapp starting ... OK
[+] Patching offsets for 71.2 ... Starting modern arch patch via bash&seek ...
[+] Patching address at offset: 0x5dccbf with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000026 secs (38480 bytes/sec)
[+] Patching address at offset: 0x5dccc2 with value: \00
1+0 records in
1+0 records out
1 bytes transferred in 0.000021 secs (47663 bytes/sec)
[+] Patching address at offset: 0x5db90e with value: \00\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000023 secs (87381 bytes/sec)
[+] Patching address at offset: 0x5dba3e with value: \165
1+0 records in
1+0 records out
1 bytes transferred in 0.000019 secs (52429 bytes/sec)
[+] Patching address at offset: 0x6cef41 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000073 secs (205603 bytes/sec)
[+] Patching address at offset: 0x6cef51 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000069 secs (188021 bytes/sec)
[+] Patching address at offset: 0xe89f98 with value: \01
1+0 records in
1+0 records out
1 bytes transferred in 0.000020 secs (49932 bytes/sec)
[+] Patching address at offset: 0xe89f9c with value: \24
1+0 records in
1+0 records out
1 bytes transferred in 0.000019 secs (52429 bytes/sec)
[+] Patching address at offset: 0xe9859c with value: \165\00
2+0 records in
2+0 records out
2 bytes transferred in 0.000025 secs (80660 bytes/sec)
[+] Patching address at offset: 0xe986bf with value: \64
1+0 records in
1+0 records out
1 bytes transferred in 0.000027 secs (36792 bytes/sec)
[+] Patching address at offset: 0xfaa308 with value: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
15+0 records in
15+0 records out
15 bytes transferred in 0.000078 secs (191813 bytes/sec)
[+] Patching address at offset: 0xfaa318 with value: \40\123\153\145\164\143\150\103\162\141\160\160\40
13+0 records in
13+0 records out
13 bytes transferred in 0.000068 secs (191319 bytes/sec)
[+] Checking user default keychain ... Exist
[+] Checking SketchCrapp identity ... Exist
[+] Skipping certificate creation ... OK
[+] Signing the patched *.app bundle. This may require root privilege.
[+] If asked, enter your login password. Choose "Always Allow" to not be asked again.
/Applications/Sketch.app: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Applications/Sketch.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Applications/Sketch.app/Contents/MacOS/sketchtool
[-] Failed to sign Sketch bundle.
[+] Automatic fix process started.
[+] Removing certificate ...
[+] Re-creating signature identity ...
[+] Generating self-signed certificate ...
Generating a 521 bit EC private key
writing new private key to 'pk.pem'
-----
[+] Creating pkcs package...
[+] Re-importing signature identity ...
[+] Importing private key and self-signed certificate
1 identity imported.
[+] Resigning application bundle again using signature identity ...
/Applications/Sketch.app: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Applications/Sketch.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Applications/Sketch.app/Contents/MacOS/sketchtool
[-] Failed to sign Sketch bundle. Automatic method failed.
[INFO] Copy the full log and open a new issue on GitHub repository: https://github.com/duraki/SketchCrapp
[+] Cleaning up file(s) ... Cleaned
[+] SketchCrapp last published date: 2021-05-05 serial 001

**Comment by elijahtsai** [comment]
Answer: https://github.com/duraki/SketchCrapp/issues/70#issuecomment-797214408
