### ISSUE TITLE
add support for sketch version 53

### ISSUE THREAD

**Issue by x2197** [duraki/SketchCrapp#87]
**Describe the request [required]**
please add support for sketch v53

**Sketch version [required]**
What is the Sketch version you want us to add?
53

**Additional context [optional]**
I am using VirtualBox to emulate macOs and run sketch.
Sketch v54 and higher use mettle api to render it's content which VirtualBox doesn't support.
but sketch v53 and lower does work so it will be helpful to add support for sketch v53

![image](https://user-images.githubusercontent.com/91653768/135397614-18b7aa61-5ec9-4cae-9297-ddb2eb8a0537.png)

**Comment by elijahtsai** [comment]
Ok, we'll look at it.

**Comment by elijahtsai** [comment]
Hi, @x2197 The new update has been implemented, you can use following one-liner to get installed. 
And please get back to us if there has any problem for using it.

```
bash -c "$(curl -s https://raw.githubusercontent.com/duraki/SketchCrapp/master/sketchcrapp.sh -o -)" -O -g 53

```

**Comment by x2197** [comment]
ok now sketch v53 is working. but it is not rendering any content in VirtualBox.

I think the sketch v53 also don't support rendering in VirtualBox.

![VirtualBox_MacOs_16_10_2021_13_49_23](https://user-images.githubusercontent.com/91653768/137580262-6d3cfdd9-5666-4e4a-b0d7-fd4256a3a361.png)

the sketch v51.2 does support rendering in VirtualBox I have tested it.
I have created a new issue please check it: [https://github.com/duraki/SketchCrapp/issues/89](https://github.com/duraki/SketchCrapp/issues/89)
