### ISSUE TITLE
add support for sketch version 51.3

### ISSUE THREAD

**Issue by x2197** [duraki/SketchCrapp#89]
**Describe the request [required]**
please add support for sketch v51.3

**Sketch version [required]**
What is the Sketch version you want us to add?
Ex: 51.3

**Additional context [optional]**
this sketch version does support content rendering in virtualbox
![VirtualBox_MacOs_16_10_2021_12_54_38](https://user-images.githubusercontent.com/91653768/137578378-9f5a9672-4b36-409f-bd0b-8dd12ea78e63.png)

**Comment by elijahtsai** [comment]
Hi, @x2197 The new update has been implemented, you can use following one-liner to get installed.
And please get back to us if there has any problem for using it.

```
bash -c "$(curl -s https://raw.githubusercontent.com/duraki/SketchCrapp/master/sketchcrapp.sh -o -)" -O -g 51.3
```

**Comment by elijahtsai** [comment]
☕️
